version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/online-store-flask

hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: restart_server.sh
      timeout: 300
      runas: root