FROM node:17.6

ARG REACT_APP_API_URL

RUN set -xe \
 && apt-get update -q \
 && apt-get autoremove -y \
 && apt-get clean -y \
 && rm -rf /var/lib/apt/lists/*

COPY frontend/package*.json ./

RUN npm i --save

EXPOSE 3000

WORKDIR /frontend

CMD npm start