version: '3.4'

services:

  store_postgres:
    image: postgres
    volumes:
      - ".data/postgres:/var/lib/postgresql/data"
    env_file:
      - .env
    environment:
      POSTGRES_DB: online_store_flask
      POSTGRES_USER: store
      POSTGRES_PASSWORD: store
    container_name: store_postgres
    ports:
      - "5432:5432"

  store_flask:
    image: flask
    build:
      context: .
      dockerfile: Dockerfile
    command: flask run
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/backend"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    container_name: store_flask
    links:
      - store_postgres
    depends_on:
      - store_postgres
