FROM node:17.9-slim as builder

EXPOSE 3000

ARG REACT_APP_API_URL

WORKDIR /app

COPY frontend/package*.json ./

RUN npm i --save

COPY frontend/ ./

RUN npm run build

FROM nginx:stable-alpine

COPY --from=builder /app/build /bin/www

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]
