version: '3.4'

services:

  store_postgres:
    image: postgres
    volumes:
      - ".data/postgres:/var/lib/postgresql/data"
    env_file:
      - .env
    environment:
      POSTGRES_DB: online_store_flask
      POSTGRES_USER: store
      POSTGRES_PASSWORD: store
    container_name: store_postgres
    ports:
      - "5432:5432"
    networks:
      - store_network

  store_flask:
    image: flask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - "./backend:/backend"
    env_file:
      - .env
    container_name: store_flask
    depends_on:
      - store_postgres
    networks:
      - store_network

  store_react:
    container_name: store_react
    build:
      context: .
      dockerfile: Dockerfile-node
      args:
        REACT_APP_API_URL: "http://localhost:8000"
    ports:
      - "80:80"
    volumes:
      - "./frontend:/frontend"
    env_file:
      - frontend/.env
    depends_on:
      - store_flask
    networks:
      - store_network

networks:
  store_network:
    driver: bridge